class _BotCommands:
    def __init__(self):
        self.StartCommand = 'start'
        self.MirrorCommand = 'mir'
        self.UnzipMirrorCommand = 'unzipmir'
        self.TarMirrorCommand = 'tar'
        self.CancelMirror = 'can'
        self.CancelAllCommand = 'batalsemua'
        self.ListCommand = 'list'
        self.StatusCommand = 'status'
        self.AuthorizedUsersCommand = 'users3'
        self.AuthorizeCommand = 'authorize3'
        self.UnAuthorizeCommand = 'unauthorize3'
        self.AddSudoCommand = 'addsudo3'
        self.RmSudoCommand = 'rmsudo3'
        self.PingCommand = 'ping'
        self.RestartCommand = 'restart3'
        self.StatsCommand = 'stats'
        self.HelpCommand = 'help3'
        self.LogCommand = 'log3'
        self.SpeedCommand = 'speedtest3'
        self.CloneCommand = 'salin'
        self.CountCommand = 'hitung'
        self.WatchCommand = 'watch3'
        self.TarWatchCommand = 'tarwatch3'
        self.DeleteCommand = 'del3'
        self.ConfigMenuCommand = 'config3'
        self.ShellCommand = 'shell3'
        self.UpdateCommand = 'update3'
        self.ExecHelpCommand = 'exechelp3'
        self.TsHelpCommand = 'tshelp3'

BotCommands = _BotCommands()
